### ISSUE TITLE
Error storing batch

### ISSUE THREAD

**Issue by 0x0ece** [0xPolygonHermez/zkevm-node#1378] opened 2022-11-08 19:31 UTC
I believe I set up a working L2 network. I followed the updated docs (the ones not merged yet).

Everything runs fine for a while, syncing from Goerli. Suddenly the container `zkevm-sync` stops on batch number 777. I destroyed everything, recreated the dbs from scratch, re-run the network... and got stuck again at the same exact place.

I can see the tx `0xeefb4590e7de5e7e554d2e48ecdaa069e436346f6add0c9a9c5569060c7ea84c` in the explorer, which suggests it's been stored in the db, hence the duplicated key. However if I re-launch the `zkevm-sync` container, it gets stuck at the same place.

I built `zkevm-sync` image from the latest commit: [4b997c0](https://github.com/0xPolygonHermez/zkevm-node/commit/4b997c05710f7a93ba7b48799b8413c9bc50d95b).

```
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	synchronizer/synchronizer.go:589	BatchNumber: 776, not found in trusted state. Storing it...
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:489	processBatch[processBatchRequest.BatchNum]: 776
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:491	processBatch[processBatchRequest.From]:
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:492	processBatch[processBatchRequest.OldStateRoot]: 0xb13fde3d621c793752c1215a26b9061f1e616613d237ff7760766aa61d4d767a
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:493	processBatch[processBatchRequest.GlobalExitRoot]: 0x283d7ec03c1b98c16a2c75c098896126b2fb021132dc720707fb89a66ee19881
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:494	processBatch[processBatchRequest.OldLocalExitRoot]: 0x6b6ef43ec13755eb2365bf264eaafc65608cc005b14f3fd5d4f889e8361ab776
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:495	processBatch[processBatchRequest.EthTimestamp]: 1665503766
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:496	processBatch[processBatchRequest.Coinbase]: 0x22Ba753CA065d65D4d0b9f4FAC7a669746175199
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:497	processBatch[processBatchRequest.UpdateMerkleTree]: 1
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:498	processBatch[processBatchRequest.ChainId]: 1402
zkevm-sync  | 2022-11-08T19:16:16Z	INFO	state/state.go:501	It took 445.70761ms for the executor to process the request
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:79	ProcessTransactionResponse[TxHash]: 0xeefb4590e7de5e7e554d2e48ecdaa069e436346f6add0c9a9c5569060c7ea84c
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:80	ProcessTransactionResponse[Nonce]: 4
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:81	ProcessTransactionResponse[StateRoot]: 0xc6c1f55930c8d17d3a2d95f3e8e156753724dec4151e182c43560311de06767b
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:82	ProcessTransactionResponse[Error]: <nil>
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:83	ProcessTransactionResponse[GasUsed]: 49560
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:84	ProcessTransactionResponse[GasLeft]: 3097
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:85	ProcessTransactionResponse[GasRefunded]: 0
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/converters.go:86	ProcessTransactionResponse[IsProcessed]: true
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	synchronizer/synchronizer.go:589	BatchNumber: 777, not found in trusted state. Storing it...
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:489	processBatch[processBatchRequest.BatchNum]: 777
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:491	processBatch[processBatchRequest.From]:
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:492	processBatch[processBatchRequest.OldStateRoot]: 0xc6c1f55930c8d17d3a2d95f3e8e156753724dec4151e182c43560311de06767b
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:493	processBatch[processBatchRequest.GlobalExitRoot]: 0x283d7ec03c1b98c16a2c75c098896126b2fb021132dc720707fb89a66ee19881
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:494	processBatch[processBatchRequest.OldLocalExitRoot]: 0x6b6ef43ec13755eb2365bf264eaafc65608cc005b14f3fd5d4f889e8361ab776
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:495	processBatch[processBatchRequest.EthTimestamp]: 1665503766
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:496	processBatch[processBatchRequest.Coinbase]: 0x22Ba753CA065d65D4d0b9f4FAC7a669746175199
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:497	processBatch[processBatchRequest.UpdateMerkleTree]: 1
zkevm-sync  | 2022-11-08T19:16:16Z	DEBUG	state/state.go:498	processBatch[processBatchRequest.ChainId]: 1402
zkevm-sync  | 2022-11-08T19:16:17Z	INFO	state/state.go:501	It took 151.169588ms for the executor to process the request
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:79	ProcessTransactionResponse[TxHash]: 0xeefb4590e7de5e7e554d2e48ecdaa069e436346f6add0c9a9c5569060c7ea84c
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:80	ProcessTransactionResponse[Nonce]: 4
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:81	ProcessTransactionResponse[StateRoot]: 0xe2e3957f4ab23d10418eceb7ffc13b9da7eedff884d6a370920ad5a539b9258c
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:82	ProcessTransactionResponse[Error]: <nil>
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:83	ProcessTransactionResponse[GasUsed]: 52657
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:84	ProcessTransactionResponse[GasLeft]: 0
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:85	ProcessTransactionResponse[GasRefunded]: 0
zkevm-sync  | 2022-11-08T19:16:17Z	DEBUG	state/converters.go:86	ProcessTransactionResponse[IsProcessed]: true
zkevm-sync  | 2022-11-08T19:16:17Z	ERROR	synchronizer/synchronizer.go:593	error storing trustedBatch. BatchNumber: 777, BlockNumber: 7751715, error: ERROR: duplicate key value violates unique constraint "transaction_pkey" (SQLSTATE 23505)
zkevm-sync  | 2022-11-08T19:16:17Z	FATAL	synchronizer/synchronizer.go:598	error storing batch. BatchNumber: 777, BlockNumber: 7751715, error: ERROR: duplicate key value violates unique constraint "transaction_pkey" (SQLSTATE 23505)
zkevm-sync exited with code 1```

**Comment by arnaubennassar** [comment] 2022-11-09 09:43
Thanks for the report! We'll investigate what's happening

**Comment by ARR552** [comment] 2022-11-10 14:46
@0x0ece  I couldn't reproduce the error. Can you provide more details? Maybe the zkevm-sync config file you are using for example. Are you using your own L1 node or infura?

**Comment by arnaubennassar** [comment] 2022-12-01 17:39
Closing as it has been 3 weeks without further news, and we haven't been able to reproduce. @0x0ece feel free to reopen if you have moer details, and thank you for the feed back

**Closed by arnaubennassar** 2022-12-01 17:39 UTC
Labels: bug
