### ISSUE TITLE
Images are getting down when Running on Locally

### ISSUE THREAD

**Issue by skardas** [0xPolygonHermez/zkevm-node#1266] opened 2022-10-12 08:13 UTC
I am trying to test your zk-EVM node on my local PC . I follow the instructions you described in https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/running_local.md. The images are build successfully but when I make it run, sequencer, json-rpc, aggregator and sync are getting shutdown.

My laptop is MacBook pro (64GB RAM) with apple silicon chip.

thanks

![image](https://user-images.githubusercontent.com/19305096/195288617-14d422a0-3a92-4832-8045-0097e0572fc1.png)

**Comment by arnaubennassar** [comment] 2022-10-12 17:02
Theoretically all images should work under M1 chips, the only one that has given problems over time is the `zkevm-prover`. Could you provide logs of the failing images? You can get them by running `docker-compose logs zkevm-mock-l1-network` and  `docker-compose logs zkevm-prover`

**Comment by skardas** [comment] 2022-10-12 21:23
![image](https://user-images.githubusercontent.com/19305096/195450666-7b64fc90-0108-47c6-beed-ca9039035344.png)

**Comment by arnaubennassar** [comment] 2022-11-02 13:40
it looks like you've problems with the `zkevm-prover` image. Most likely due to using M1 chip or Windows OS... Is this the case?

**Comment by arnaubennassar** [comment] 2022-12-01 17:39
Closing as the problem is related to hardware requirements

**Closed by arnaubennassar** 2022-12-01 17:39 UTC
